config/routes.rb
Rails.application.routes.draw do
  root to: "top#index"
  devise_for :users
  resources :users, only: [:show, :edit, :update] do
    get :favorites, on: :collection
  end
  resources :shops, only: [:index, :show] do
    resource :favorites, only: [:create, :destroy]
    resources :rooms, only: [:index, :new, :create, :show, :destroy] do
      resources :messages, only: [:index, :create]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :shop

  validates_uniqueness_of :shop_id, scope: :user_id
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :shop, optional:true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :room
  belongs_to :user
  mount_uploader :image, ImageUploader

  validates :content, presence: true, unless: :was_attached?

  def was_attached?
    self.image.cached?
  end
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :shop
  has_many :room_users
  has_many :users, through: :room_users
  has_many :messages
end

app/models/room_user.rb
class RoomUser < ApplicationRecord
  belongs_to :room
  belongs_to :user
end

app/models/shop.rb
class Shop < ApplicationRecord
  has_many :rooms
  has_many :images, dependent: :destroy
  has_many :users, through: :favorites, dependent: :destroy
  has_many :favorites, dependent: :destroy

  def favorite_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :room_users
  has_many :rooms, through: :room_users
  has_many :messages
  has_many :shops, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_shops, through: :favorites, source: :shop

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def after_sign_up_path_for(resource) 
    shops_path
  end

  def after_sign_in_path_for(resource) 
    shops_path
  end

  protected

    def configure_permitted_parameters
      added_attrs = [ :email, :nickname, :password, :password_confirmation ]
      devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
      devise_parameter_sanitizer.permit :account_update, keys: added_attrs
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :set_shop
  before_action :authenticate_user!   # ログイン中のユーザーのみに許可（未ログインなら、ログイン画面へ移動）

  # お気に入り登録
  def create
    if Favorite.create(user_id: @user.id,shop_id:@shop.id)
      flash[:success] = "登録完了しました！"
      redirect_to shop_path(@shop.id)
    else
        redirect_to root_path
    end
  end
  # お気に入り削除
  def destroy
    if favorite=Favorite.find_by(user_id: @user.id,shop_id:@shop.id)
      favorite.delete
      flash[:success] = "登録解除しました！"
      redirect_to shop_path(@shop.id)
    else
      redirect_to root_path
    end
  end

  private
  def set_shop
    @user = current_user
    @shop = Shop.find(params[:shop_id])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def index
    @message = Message.new
    @shop = Shop.find(params[:shop_id])
    @room = Room.find(params[:room_id])
    @rooms = @shop.rooms.all.order(id: "DESC")
    @messages = @room.messages.includes(:user)
  end

  def create
    @room = Room.find(params[:room_id])
    @message = @room.messages.new(message_params)
    if @message.save
      redirect_to action: 'index'
    else
      @messages = @room.messages.includes(:user)
      render :index
    end
  end

  private

  def message_params
    params.require(:message).permit(:content, :image).merge(user_id: current_user.id)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_shop

  def index
    @rooms = @shop.rooms.all.order(id: "DESC")
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)
    if @room.save
      redirect_to action: :index
    else
      render action: :new
    end
  end

  def destroy
    room = Room.find(params[:id])
    room.destroy
    redirect_to action: :index
  end

  def show
    @room = Room.find(params[:id])
    @messages = @room.messages
  end

  private

  def set_shop
    @shop = Shop.find(params[:shop_id])
  end

  def room_params
    params.require(:room).permit(:name, user_ids: []).merge(shop_id: params[:shop_id])
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :set_shop, only: [:show]
  before_action :authenticate_user!

  def index
    @user = current_user
    # binding.pry
    @shops = Shop.all.includes(:images)
  end

  def show
  end

  private
    def set_shop
      @shop = Shop.find(params[:id])
    end

    def shop_params
      params.require(:shop).permit(:name, :tel, :address)
    end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  before_action :move
  
  def index
  end

  private
  def move
    if user_signed_in?
      redirect_to  shops_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @shops = @user.shops

    favorites = Favorite.where(user_id: current_user.id).pluck(:shop_id)  # ログイン中のユーザーのお気に入りのshop_idカラムを取得
    @favorite_list = Shop.find(favorites)     # shopsテーブルから、お気に入り登録済みのレコードを取得
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/messages/_message.html.erb
<div class="chat-header">
  <div class="left-header">
    <div class="header-title">
      <p>ルーム名：<%= @room.name%></p>
    </div>
  </div>
  <div class="right-header">
    <div class="header-button">
      <%= link_to "ルームを出る", shop_rooms_path(@shop) %>
    </div>
  </div>
</div>

<div class="messages">
  <div class="chat__wrapper">
    <div class="chat__content">
      <% @messages.each do |message| %>
        <%# --自分のメッセージ-- %>
        <% if message.user_id == current_user.id %>
          <div class="chat__message__content" data-message-id= <%=message.id %>>
            <div class="chat__message__right">
              <%# image_tag current_user.picture.url, id: "message__right__user__image" %>
              <div class="chat__message__right__content">
                <%= message.content %> 
              </div>
            </div>
            <div class='message-image-right'>
              <%= image_tag message.image.to_s %>
            </div>
            <div class="message__right__created">
              <%= message.created_at.strftime("%m月%d日 %H時%M分") %>
            </div>
          </div>
        <% else %>
          <%# --相手のメッセージ-- %>
          <div class="chat__message__content" data-message-id= <%=message.id %>>
            <div class=message__left__name>
              <%= message.user.nickname %>
            </div>
            <div class="chat__msessage__left">
              <%# image_tag message.user.picture.url, id: "message__left__user__image" %>
              <div class="chat__message__left__content">
                <%= message.content %> 
              </div>
              <%# image_tag message.image.to_s.variant(resize:'500x500'), class: 'message-image' if message.image.to_s.attached? %>
            </div>
            <div class='message-image-left'>
              <%= image_tag message.image.to_s %>
            </div>
            <div class="message__left__created">
              <%= message.created_at.strftime("%m月%d日 %H:%M") %>
            </div> 
          </div>
        <% end %>
      <% end %>
      </div>
    </div>
  </div>
  <%= form_with model: [@shop, @room, @message], html: {class: "form"}, local: true do |f|%>
    <div class="form-input">
      <%= f.text_field :content, class: 'form-message', placeholder: 'type a message' %>
      <label class="form-image">
        <span class="image-file">画像</span>
        <%= f.file_field :image, class: 'hidden' %>
      </label>
    </div>
    <%= f.submit '送信', class: 'form-submit' %>
  <% end %>
</div>

app/views/messages/index.erb
<%= render "shared/header_chat" %>

<div class="wrapper">
  <div class="side-bar">
    <%= render "shared/side_bar" %>
  </div>
  <div class="chat">
    <%= render "message" %>
  </div>
</div>

<%= render "shared/footer" %>

app/views/rooms/index.html.erb
<%= render "shared/header_chat" %>

<div class="wrapper">
  <div class="side-bar">
    <%= render "shared/side_bar" %>
  </div>
</div>

<%= render "shared/footer" %>

app/views/rooms/new.html.erb
<%= render "shared/header_chat" %>

<div class='chat-room-form'>
  <h1>新規チャットルーム</h1>
  <%=form_with(model: [@shop, @room], local: true) do |f|%>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <%= f.label :チャットルーム名, class: 'chat-room-form__label'%>
      </div>
      <div class='chat-room-form__field--right'>
        <%= f.text_field :name, class: 'chat__room_name chat-room-form__input', placeholder: 'チャットルーム名を入力してください'%>
      </div>
    </div>
    <div class='chat-room-form__field'>
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'></div>
      <div class='chat-room-form__field--right'>
        <%= f.submit class: 'chat-room-form__action-btn'%>
      </div>
    </div>
  <% end %>
</div>
<%= render "shared/footer" %>

app/views/rooms/show.html.erb
<h1>Chat room</h1>
<div id='messages' data-room_id="<%= @room.id %>">
  <%= render @messages %>
</div>

<%= label_tag :content, 'Say something:' %>
<%= text_field_tag :content, nil, data: { behavior: 'room_speaker' } %>

app/views/shops/index.html.erb
<%= render "shared/header_main" %>

<main role="main">

  <div class="main_map">
    <div id='map'>
    </div>
  </div>
  <%= render "shared/footer" %>

  <script>
    let map;
    // 現在地取得処理
    function initMap() {
      // Geolocation APIに対応している
      if (navigator.geolocation) {
        // 現在地を取得
        navigator.geolocation.getCurrentPosition(
          // 取得成功した場合
          function(position) {
            // 緯度・経度を変数に格納
            let mapLatLng = new google.maps.LatLng(position.coords.latitude, position.coords.longitude);
            // マップオプションを変数に格納
            let mapOptions = {
              zoom : 14,          // 拡大倍率
              center : mapLatLng  // 緯度・経度
            };
            // マップオブジェクト作成
            map = new google.maps.Map(
              document.getElementById('map'), // マップを表示する要素
              mapOptions         // マップオプション
            );
            // マップにマーカーを表示する
            let marker = new google.maps.Marker({
              map : map,             // 対象の地図オブジェクト
              position : mapLatLng,   // 緯度・経度
              icon: {
              url: ' http://maps.google.co.jp/mapfiles/ms/icons/red-pushpin.png', //アイコンのURL
              scaledSize: new google.maps.Size(40, 40) //サイズ
              }
            });
            // 複数マーカー
            <% @shops.each do |shop| %>
              (function(){
                let contentString = '<div id="content" class="map-content">'+
                  '<div class="map-category">'+
                  '<p><%= shop.category %></p>'+
                  '</div>'+
                  '<div class="map-name">'+
                  '<%= link_to shop_path(shop.id), method: :get do %>'+
                  '<p><b><%= shop.name %></b></p>'+
                  '<% end %>'+
                  '</div>'+
                  '<%= image_tag shop.images[0].src.to_s, class: "map-img", :size =>'150x125'%>'
                  '</div>';

                let marker_shop = new google.maps.Marker({
                  position:{lat: <%= shop.latitude %>, lng: <%= shop.longitude %>},
                  map: map,
                  title: contentString, 
                  icon: {
                  url: ' http://maps.google.com/mapfiles/kml/pal2/icon19.png', //アイコンのURL
                  scaledSize: new google.maps.Size(40, 40) //サイズ
                  }
                });

                let infowindow = new google.maps.InfoWindow({
                  position:{lat: <%= shop.latitude %>, lng: <%= shop.longitude %>},
                  content: contentString
                });
                  marker_shop.addListener('click', function() {
                  infowindow.open(map, marker_shop);
                });
              })();
            <% end %>
          },

          // 取得失敗した場合
          function(error) {
            // エラーメッセージを表示
            switch(error.code) {
              case 1: // PERMISSION_DENIED
                alert("位置情報の利用が許可されていません");
                break;
              case 2: // POSITION_UNAVAILABLE
                alert("現在位置が取得できませんでした");
                break;
              case 3: // TIMEOUT
                alert("タイムアウトになりました");
                break;
              default:
                alert("その他のエラー(エラーコード:"+error.code+")");
                break;
            }
          },

          {
            enableHighAccuracy: true,
          }
        );
      } else {
        // Geolocation APIに対応していない
        alert("この端末では位置情報が取得できません");
      }
    }
  </script>
</main>

app/views/shops/show.html.erb
<%= render "shared/header_show" %>
<div class="show-main">
  <div class='show-header'>
    <div class='show-title'>
      <div class='shop-category'>
        <p>~<%= @shop.category %>~</p>
      </div>

      <div class='shop-name'>
        <%= @shop.name %>
      </div>
    </div>

    <div class='show-menu'>
      <div class='shop-tel'>
        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-telephone-forward" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
          <path fill-rule="evenodd" d="M3.654 1.328a.678.678 0 0 0-1.015-.063L1.605 2.3c-.483.484-.661 1.169-.45 1.77a17.568 17.568 0 0 0 4.168 6.608 17.569 17.569 0 0 0 6.608 4.168c.601.211 1.286.033 1.77-.45l1.034-1.034a.678.678 0 0 0-.063-1.015l-2.307-1.794a.678.678 0 0 0-.58-.122l-2.19.547a1.745 1.745 0 0 1-1.657-.459L5.482 8.062a1.745 1.745 0 0 1-.46-1.657l.548-2.19a.678.678 0 0 0-.122-.58L3.654 1.328zM1.884.511a1.745 1.745 0 0 1 2.612.163L6.29 2.98c.329.423.445.974.315 1.494l-.547 2.19a.678.678 0 0 0 .178.643l2.457 2.457a.678.678 0 0 0 .644.178l2.189-.547a1.745 1.745 0 0 1 1.494.315l2.306 1.794c.829.645.905 1.87.163 2.611l-1.034 1.034c-.74.74-1.846 1.065-2.877.702a18.634 18.634 0 0 1-7.01-4.42 18.634 18.634 0 0 1-4.42-7.009c-.362-1.03-.037-2.137.703-2.877L1.885.511zm10.762.135a.5.5 0 0 1 .708 0l2.5 2.5a.5.5 0 0 1 0 .708l-2.5 2.5a.5.5 0 0 1-.708-.708L14.293 4H9.5a.5.5 0 0 1 0-1h4.793l-1.647-1.646a.5.5 0 0 1 0-.708z"/>
        </svg>
        <%= @shop.tel %>
      </div>

      <div class='shop-pr_short'>
        <%= @shop.pr_short %>
      </div>
      
      <div class='show-link'>
        <%= link_to 'チャットルームへ', shop_rooms_path(@shop), class: "show-link-btn" %>

        <% if !Favorite.exists?(user_id:current_user.id,shop_id:@shop.id) %>
          <%= link_to "お気に入り",shop_favorites_path(@shop),method: :post, class: "show-link-btn" %>
        <% else %>
          <%= link_to "お気に入り解除",shop_favorites_path(@shop),method: :delete, class: "show-link-btn" %>
        <% end %>
      </div>
    </div>
  </div>

  <div class='shop-img'>
    <% @shop.images.each do |image| %>
      <div class='shop-img-count'>
        <%= image_tag image.src, size: '300x250'%>
      </div>
    <% end %>
  </div>


  <table>
    <tr>
      <th>営業時間</th>
      <td><%= @shop.open_time %></td>
    </tr>
    <tr>
      <th>定休日</th>
      <td><%= @shop.holiday %></td>
    </tr>
    <tr>
      <th>電話番号</th>
      <td><%= @shop.tel %></td>
    </tr>
    <tr>
      <th>住所</th>
      <td><%= @shop.address %></td>
    </tr>
      <th>PR</th>
      <td><%= @shop.pr_long %></td>
    </tr>
    </tr>
      <th>URL</th>
      <td><%= link_to @shop.url, @shop.url %></td>
    </tr>
  </table>
</div>

<div id='show_map'>
</div>

<%= render "shared/footer" %>

<script>
  // 現在地取得処理
  function initMap() {
    // Geolocation APIに対応している
    if (navigator.geolocation) {
      // 現在地を取得
      navigator.geolocation.getCurrentPosition(
        // 取得成功した場合
        function(position) {
          // 緯度・経度を変数に格納
          const mapLatLng = new google.maps.LatLng(position.coords.latitude, position.coords.longitude);
          // マップオプションを変数に格納
          const mapOptions = {
            zoom : 14,          // 拡大倍率
            center : mapLatLng  // 緯度・経度
          };
          const test ={lat: <%= @shop.latitude %>, lng: <%= @shop.longitude %>};
          const contentString = '住所：<%= @shop.address %>';
          // マップオブジェクト作成
          const map = new google.maps.Map(
            document.getElementById("show_map"), // マップを表示する要素
            mapOptions         // マップオプション
          );
          // マップにマーカーを表示する
          const marker = new google.maps.Marker({
            map : map,             // 対象の地図オブジェクト
            position : mapLatLng,   // 緯度・経度
            icon: {
            url: ' http://maps.google.co.jp/mapfiles/ms/icons/red-pushpin.png', //アイコンのURL
            scaledSize: new google.maps.Size(40, 40) //サイズ
            }
          });
          const marker_shop = new google.maps.Marker({
            position:test,
            map: map,
            title: contentString,
            icon: {
            url: ' http://maps.google.com/mapfiles/kml/pal2/icon19.png', //アイコンのURL
            scaledSize: new google.maps.Size(40, 40) //サイズ
            }
          });
        },
        // 取得失敗した場合
        function(error) {
          // エラーメッセージを表示
          switch(error.code) {
            case 1: // PERMISSION_DENIED
              alert("位置情報の利用が許可されていません");
              break;
            case 2: // POSITION_UNAVAILABLE
              alert("現在位置が取得できませんでした");
              break;
            case 3: // TIMEOUT
              alert("タイムアウトになりました");
              break;
            default:
              alert("その他のエラー(エラーコード:"+error.code+")");
              break;
          }
        }
      );
    // Geolocation APIに対応していない
    } else {
      alert("この端末では位置情報が取得できません");
    }
  }
</script>

app/views/top/index.html.erb
<main role="main">

  <div class="top_main">
    <div class="text-center">
      <div class="inner cover">
        <h1 class="cover-heading"><span>nomi_tomo</span></h1>
        <p class="lead">It is an application that aims to make drinking friends for people who are lonely to drink alone, such as wanting to go drinking nearby on holidays or wanting drinking friends.</p>
        <p class="lead">
          <%= link_to "ログイン", new_user_session_path, class: "btn btn-lg btn-secondary" %>
          <%= link_to "新規登録", new_user_registration_path, class: "btn btn-lg btn-secondary" %>
        </p>
      </div>
    </div>
  </div>
</main>
<%= render "shared/footer" %>

app/views/users/show.html.erb
<%= render "shared/header_mypage" %>

<div class="mypage">
  <div class="album py-5 bg-light">
    <div class="container">

      <div class="row">
        <% if @favorite_list.present? %>
          <% @favorite_list.each do |shop| %>
            <div class="col-md-4">
              <div class="card mb-4 shadow-sm">
                <%= image_tag shop.images[0].src.to_s, class: "card-img-top", :size =>'288x230' %>
                <div class="card-body">
                  <p class="card-text"><b><%= shop.name %></b></p>
                  <p class="card-text">〜<%= shop.category %>〜</p>
                  <p class="card-text">住所：<%= shop.address %></p>
                  <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                      <%= link_to "詳細", shop_path(shop.id), method: :get, class: "btn btn-sm btn-outline-secondary" %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<%= render "shared/footer" %>