config/routes.rb
Rails.application.routes.draw do
  root to: "top#index"
  devise_for :users
  resources :users, only: [:show, :edit, :update] do
    get :favorites, on: :collection
  end
  resources :shops, only: [:index, :show] do
    resource :favorites, only: [:create, :destroy]
    resources :rooms, only: [:index, :new, :create, :show, :destroy] do
      resources :messages, only: [:index, :create]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :shop

  validates_uniqueness_of :shop_id, scope: :user_id
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :shop, optional:true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :room
  belongs_to :user
  mount_uploader :image, ImageUploader

  validates :content, presence: true, unless: :was_attached?

  def was_attached?
    self.image.cached?
  end
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :shop
  has_many :room_users
  has_many :users, through: :room_users
  has_many :messages
end

app/models/room_user.rb
class RoomUser < ApplicationRecord
  belongs_to :room
  belongs_to :user
end

app/models/shop.rb
class Shop < ApplicationRecord
  has_many :rooms
  has_many :images, dependent: :destroy
  has_many :users, through: :favorites, dependent: :destroy
  has_many :favorites, dependent: :destroy

  def favorite_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :room_users
  has_many :rooms, through: :room_users
  has_many :messages
  has_many :shops, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_shops, through: :favorites, source: :shop

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :set_shop
  before_action :authenticate_user!   # ログイン中のユーザーのみに許可（未ログインなら、ログイン画面へ移動）

  # お気に入り登録
  def create
    if Favorite.create(user_id: @user.id,shop_id:@shop.id)
      flash[:success] = "登録完了しました！"
      redirect_to shop_path(@shop.id)
    else
        redirect_to root_path
    end
  end
  # お気に入り削除
  def destroy
    if favorite=Favorite.find_by(user_id: @user.id,shop_id:@shop.id)
      favorite.delete
      flash[:success] = "登録解除しました！"
      redirect_to shop_path(@shop.id)
    else
      redirect_to root_path
    end
  end

  private
  def set_shop
    @user = current_user
    @shop = Shop.find(params[:shop_id])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def index
    @message = Message.new
    @shop = Shop.find(params[:shop_id])
    @room = Room.find(params[:room_id])
    @rooms = @shop.rooms.all.order(id: "DESC")
    @messages = @room.messages.includes(:user)
  end

  def create
    @room = Room.find(params[:room_id])
    @message = @room.messages.new(message_params)
    if @message.save
      redirect_to action: 'index'
    else
      @messages = @room.messages.includes(:user)
      render :index
    end
  end

  private

  def message_params
    params.require(:message).permit(:content, :image).merge(user_id: current_user.id)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_shop

  def index
    @rooms = @shop.rooms.all.order(id: "DESC")
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)
    if @room.save
      redirect_to action: :index
    else
      render action: :new
    end
  end

  def destroy
    room = Room.find(params[:id])
    room.destroy
    redirect_to action: :index
  end

  def show
    @room = Room.find(params[:id])
    @messages = @room.messages
  end

  private

  def set_shop
    @shop = Shop.find(params[:shop_id])
  end

  def room_params
    params.require(:room).permit(:name, user_ids: []).merge(shop_id: params[:shop_id])
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :set_shop, only: [:show]
  before_action :authenticate_user!

  def index
    @user = current_user
    # binding.pry
    @shops = Shop.all.includes(:images)
  end

  def show
  end

  private
    def set_shop
      @shop = Shop.find(params[:id])
    end

    def shop_params
      params.require(:shop).permit(:name, :tel, :address)
    end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  before_action :move
  
  def index
  end

  private
  def move
    if user_signed_in?
      redirect_to  shops_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @shops = @user.shops

    favorites = Favorite.where(user_id: current_user.id).pluck(:shop_id)  # ログイン中のユーザーのお気に入りのshop_idカラムを取得
    @favorite_list = Shop.find(favorites)     # shopsテーブルから、お気に入り登録済みのレコードを取得
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>nomi_tomo</title>
    <meta charset="utf-8">
    <%= csrf_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAP_API_KEY']%>&callback=initMap" async defer></script>
  </body>
</html>

app/views/shared/_footer.html.erb
<footer class="footer mt-auto py-3">
  <div class="container">
    <p class="float-right"><a href="/">Back to top</a></p>
    <p>2020 application work "nomi_tomo"</p>
  </div>
</footer>

app/views/shared/_header.html.erb
<header>
  <div class="collapse bg-dark" id="navbarHeader">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-md-7 py-4">
          <h4 class="text-white">メインページ</h4>
          <p class="text-muted">現在地周辺の居酒屋をMap上で表示させます。アイコンをクリックで店名が表示されますので、店名をクリックする事でお店の詳細ページへ遷移します。</p>
        </div>
        <div class="col-sm-4 offset-md-1 py-4">
          <h4 class="text-white">メニュー</h4>
          <div class="list-unstyled">
            <p><a href="#" class="text-white">マイページ</a></p>
            <p><a href="#" class="text-white">フレンド一覧</a></p>
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "text-white" %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="navbar navbar-dark bg-dark shadow-sm">
    <div class="container d-flex justify-content-between">
      <a href="/" class="navbar-brand d-flex align-items-center">
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mr-2"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"></path><circle cx="12" cy="13" r="4"></circle></svg>
        <strong>nomi_tomo</strong>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </div>
</header>

app/views/shared/_header_chat.html.erb
<header>
  <div class="collapse bg-dark" id="navbarHeader">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-md-7 py-4">
          <h4 class="text-white">チャットルーム</h4>
          <p class="text-muted">店舗ごとのコミュニティーツールとしてご利用いただけます。ルーム作成したり、ルームへ参加したりして各々の交流を深めたり、出会いの場としての活用も可能です。</p>
        </div>
        <div class="col-sm-4 offset-md-1 py-4">
          <h4 class="text-white">メニュー</h4>
          <div class="list-unstyled">
            <%= link_to "マイページ", "/users/#{current_user.id}", class: "text-white" %>
            <p><a href="#" class="text-white">フレンド一覧</a></p>
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "text-white" %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="navbar navbar-dark bg-dark shadow-sm">
    <div class="container d-flex justify-content-between">
      <a href="/" class="navbar-brand d-flex align-items-center">
        <strong>nomi_tomo</strong>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </div>
</header>

app/views/shared/_header_main.html.erb
<header>
  <div class="collapse bg-dark" id="navbarHeader">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-md-7 py-4">
          <h4 class="text-white">メインページ</h4>
          <p class="text-muted">現在地周辺の居酒屋をMap上で表示させます。アイコンをクリックで店名が表示されますので、店名をクリックする事でお店の詳細ページへ遷移します。</p>
        </div>
        <div class="col-sm-4 offset-md-1 py-4">
          <h4 class="text-white">メニュー</h4>
          <div class="list-unstyled">
            <%= link_to "マイページ", "/users/#{current_user.id}", class: "text-white" %>
            <p><a href="#" class="text-white">フレンド一覧</a></p>
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "text-white" %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="navbar navbar-dark bg-dark shadow-sm">
    <div class="container d-flex justify-content-between">
      <a href="/" class="navbar-brand d-flex align-items-center">
        <strong>nomi_tomo</strong>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </div>
</header>

app/views/shared/_header_mypage.html.erb
<header>
  <div class="collapse bg-dark" id="navbarHeader">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-md-7 py-4">
          <h4 class="text-white">マイページ</h4>
          <p class="text-muted">お気に入り登録された店舗一覧が表示されます。一覧から店舗詳細ページへアクセスします。</p>
        </div>
        <div class="col-sm-4 offset-md-1 py-4">
          <h4 class="text-white">メニュー</h4>
          <div class="list-unstyled">
            <%= link_to "メインページ", root_path, class: "text-white" %>
            <p><a href="#" class="text-white">フレンド一覧</a></p>
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "text-white" %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="navbar navbar-dark bg-dark shadow-sm">
    <div class="container d-flex justify-content-between">
      <a href="/" class="navbar-brand d-flex align-items-center">
        <strong>nomi_tomo</strong>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </div>
</header>

app/views/shared/_header_show.html.erb
<header>
  <div class="collapse bg-dark" id="navbarHeader">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-md-7 py-4">
          <h4 class="text-white">詳細ページ</h4>
          <p class="text-muted">店舗情報の詳細を表示します。アクセス用のMapを表示、店舗のチャットルームへの遷移ボタンがあります。</p>
        </div>
        <div class="col-sm-4 offset-md-1 py-4">
          <h4 class="text-white">メニュー</h4>
          <div class="list-unstyled">
            <%= link_to "マイページ", "/users/#{current_user.id}", class: "text-white" %>
            <p><a href="#" class="text-white">フレンド一覧</a></p>
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "text-white" %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="navbar navbar-dark bg-dark shadow-sm">
    <div class="container d-flex justify-content-between">
      <a href="/" class="navbar-brand d-flex align-items-center">
        <strong>nomi_tomo</strong>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </div>
</header>

app/views/shared/_side_bar.html.erb
<div class="side-bar-header">
  <div class="header-shop">
    <%= image_tag @shop.images[0].src.to_s, class: "header-shop-img", :size =>'200x160' %>
    <p class="header-shop-category">〜<%= @shop.category %>〜</p>
    <p class="header-shop-name"><b><%= @shop.name %></b></p>
  </div>
  <div class="header-info">
    <div class="header-name">
      <%= link_to current_user.nickname, user_path(current_user.id) %>
    </div>
    <div class="create-room">
      <%= link_to "チャットを作成する", new_shop_room_path %>
    </div>
  </div>
</div>

<div class="rooms">
  <% @rooms.each do |room| %>
    <div class="room">
      <div class="room-name">
        <%= link_to room.name, shop_room_messages_path(room.shop_id, room.id) %>
      </div>
    </div>
  <% end %>
</div>